markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: joesir.github.io
title: Joe's Blog
description: OC,Swift,Python,C,C++,reading...
author: Joe
email: jiangzhili008@gmail.com
github: joesir

config:
  js_dir:
  img_dir:
  css_dir:
